interface ImageType {
  url: string;
  width: number;
  height: number;
}

export interface Post {
  approved_at_utc: string | null;
  subreddit: string;
  selftext: string;
  author_fullname: string;
  saved: boolean;
  mod_reason_title: string | null;
  gilded: number;
  clicked: boolean;
  title: string;
  link_flair_richtext: string[] | { e: string; t: string }[];
  subreddit_name_prefixed: string;
  hidden: boolean;
  pwls: number;
  link_flair_css_class: string | null;
  downs: number;
  thumbnail_height: number | null;
  top_awarded_type: string | null;
  hide_score: boolean;
  name: string;
  quarantine: boolean;
  link_flair_text_color: string;
  upvote_ratio: number;
  author_flair_background_color: string | null;
  subreddit_type: string;
  ups: number;
  total_awards_received: number;
  media_embed: unknown;
  thumbnail_width: number | null;
  author_flair_template_id: string | null;
  is_original_content: boolean;
  user_reports: string[];
  secure_media: unknown | null;
  is_reddit_media_domain: boolean;
  is_meta: boolean;
  category: unknown | null;
  secure_media_embed: unknown;
  link_flair_text: string | null;
  can_mod_post: boolean;
  score: number;
  approved_by: string | null;
  author_premium: boolean;
  thumbnail: string;
  edited: number | false;
  author_flair_css_class: string | null;
  author_flair_richtext: string[] | { e: string; u: string; a: string }[];
  gildings: unknown;
  post_hint?: string;
  content_categories: string[] | null;
  is_self: boolean;
  mod_note: string | null;
  created: number;
  link_flair_type: string;
  /** wtf is this */
  wls: number;
  removed_by_category: unknown | null;
  banned_by: string | null;
  author_flair_type: string;
  domain: string;
  allow_live_comments: boolean;
  selftext_html: string | null;
  likes: unknown | null;
  suggested_sort: unknown | null;
  banned_at_utc: string | null;
  view_count: number | null;
  archived: boolean;
  no_follow: boolean;
  is_crosspostable: boolean;
  pinned: boolean;
  over_18: boolean;
  preview?: {
    images: {
      source: ImageType;
      resolutions: ImageType[];
      variants: unknown;
      id: string;
    }[];
    enabled: boolean;
  };
  all_awardings: {
    giver_coin_reward: unknown | null;
    subreddit_id: string | null;
    is_new: boolean;
    days_of_drip_extension: number;
    coin_price: number;
    id: string;
    penny_donate: unknown | null;
    award_sub_type: string;
    coin_reward: number;
    icon_url: string;
    days_of_premium: number;
    tiers_by_required_awardings: unknown | null;
    resized_icons: ImageType[];
    icon_width: number;
    static_icon_width: number;
    start_date: string | null;
    is_enabled: boolean;
    awardings_required_to_grant_benefits: boolean | null;
    description: string;
    end_date: string | null;
    subreddit_coin_reward: number;
    count: number;
    static_icon_height: number;
    name: string;
    resized_static_icons: ImageType[];
    icon_format: unknown | null;
    icon_height: number;
    penny_price: number | null;
    award_type: string;
    static_icon_url: string;
  }[];
  awarders: unknown[];
  media_only: boolean;
  can_gild: boolean;
  spoiler: boolean;
  locked: boolean;
  author_flair_text: string | null;
  treatment_tags: unknown[];
  visited: boolean;
  removed_by: string | null;
  num_reports: number | null;
  distinguished: string | null;
  subreddit_id: string;
  mod_reason_by: string | null;
  removal_reason: string | null;
  link_flair_background_color: string;
  id: string;
  is_robot_indexable: boolean;
  report_reasons: unknown | null;
  author: string;
  discussion_type: unknown | null;
  num_comments: number;
  send_replies: boolean;
  whitelist_status: number | string;
  contest_mode: boolean;
  mod_reports: string[];
  author_patreon_flair: boolean;
  author_flair_text_color: string | null;
  permalink: string;
  parent_whitelist_status: string;
  stickied: boolean;
  url: string;
  subreddit_subscribers: number;
  created_utc: number;
  num_crossposts: number;
  media: unknown | null;
  is_video: boolean;
  url_overridden_by_dest?: string;
  link_flair_template_id?: string;
  crosspost_parent_list?: any[];
  crosspost_parent?: string;
  is_gallery?: boolean;
  media_metadata?: any;
  gallery_data?: {
    items: {
      media_id: string;
      id: number;
    }[];
  };
}

export interface Subreddit {
  user_flair_background_color: string | null;
  submit_text_html: string | null;
  restrict_posting: boolean;
  user_is_banned: boolean;
  free_form_reports: boolean;
  wiki_enabled: boolean | null;
  user_is_muted: boolean;
  user_can_flair_in_sr: boolean | null;
  display_name: string;
  header_img: string | null;
  title: string;
  allow_galleries: boolean;
  icon_size: unknown;
  primary_color: string;
  active_user_count: number | null;
  icon_img: string;
  display_name_prefixed: string;
  accounts_active: number | null;
  public_traffic: boolean;
  subscribers: number;
  user_flair_richtext: string[] | { e: string; t: string }[];
  videostream_links_count?: number;
  name: string;
  quarantine: boolean;
  hide_ads: boolean;
  emojis_enabled: boolean;
  advertiser_category: string;
  public_description: string;
  comment_score_hide_mins: number;
  allow_predictions: boolean;
  user_has_favorited: boolean;
  user_flair_template_id: unknown;
  community_icon: string;
  banner_background_image: string;
  original_content_tag_enabled: boolean;
  submit_text: string;
  description_html: string | null;
  spoilers_enabled: boolean;
  header_title: string | null;
  header_size: unknown;
  user_flair_position: 'left' | 'right';
  all_original_content: boolean;
  has_menu_widget: boolean;
  is_enrolled_in_new_modmail: boolean | null;
  key_color: string;
  can_assign_user_flair: boolean;
  created: number;
  wls: number | null;
  show_media_preview: boolean;
  submission_type: string;
  user_is_subscriber: boolean;
  disable_contributor_requests: boolean;
  allow_videogifs: boolean;
  user_flair_type: string | { e: string; t: string };
  allow_polls: boolean;
  collapse_deleted_comments: boolean;
  emojis_custom_size: unknown;
  public_description_html: string | null;
  allow_videos: boolean;
  is_crosspostable_subreddit: boolean | null;
  notification_level: string | null;
  can_assign_link_flair: boolean;
  accounts_active_is_fuzzed: boolean;
  submit_text_label: string | null;
  link_flair_position: string | null;
  user_sr_flair_enabled: boolean | null;
  user_flair_enabled_in_sr: boolean;
  allow_chat_post_creation?: boolean;
  allow_discovery: boolean;
  user_sr_theme_enabled: boolean;
  link_flair_enabled: boolean;
  subreddit_type: 'public' | 'user' | 'private' | 'restricted';
  suggested_comment_sort: unknown;
  banner_img: string | null;
  user_flair_text: string | { e: string; t: string } | null;
  banner_background_color: string;
  show_media: boolean;
  id: string;
  user_is_moderator: boolean;
  over18: boolean;
  description: string;
  is_chat_post_feature_enabled?: boolean;
  submit_link_label: string | null;
  user_flair_text_color: string | { e: string; t: string } | null;
  restrict_commenting: boolean;
  user_flair_css_class: string | null;
  allow_images: boolean;
  lang: string;
  whitelist_status: string | null;
  url: string;
  created_utc: number;
  banner_size: unknown;
  mobile_banner_image: string;
  user_is_contributor: boolean;
  prediction_leaderboard_entry_type: string | null;
  allow_predictions_tournament: boolean | null;
  content_category?: string;
  is_default_icon?: boolean;
  collections_enabled?: boolean;
  event_posts_enabled?: boolean;
  mod_permissions?: string[];
  coins?: number;
  is_default_banner?: boolean;
}
